
### Loading Libraries 
```{r}
library(ggplot2)
library(tidyverse)
library(DHARMa)
library(mgcv)
library(fitdistrplus)
library(goft)
library(gamlss)
library(patchwork)
library(MASS)
```


### ALARIA ###

### SPORE SETTLEMENT TRIAL 1

```{r}
# loading all data
all_data <- read.csv("data/all_settlement_data.csv")

# filtering to only include Alaria
alaria_trial_all_data <- all_data %>%
  filter(Species == "Alaria", .preserve = FALSE)

# parsing data such that only trial 1 is present 
    # Note: trial one is now the combination of trial 1 and trial 2 because they
          # both used the same batch of spores
alaria_trial1_2_data <- alaria_trial_all_data %>%
  filter(Trial.Number == "1" | Trial.Number == "2", .preserve = FALSE)

```

```{r}
#loading colours for graph
my_cols1 = c("Sound A" = "khaki2", "Sound B" = "khaki1", "Control A-B" = "indianred3")

# making graph from trial 1/2
ggplot(alaria_trial1_2_data, aes(x = Treatment, y = Settlement, fill = Treatment)) + 
  geom_point(aes(colour = Treatment), position = position_jitterdodge()) +
  geom_boxplot(alpha = 0.6) +
  scale_color_manual(values = my_cols1) +
  scale_fill_manual(values = my_cols1) + 
  theme_classic() +
  labs(x = "Treatments", y = "Spore Settlement") +
  theme(axis.title = element_text(size = 10)) +
  scale_x_discrete(labels = c("Control", "20 kHz A", "20 kHz B")) +
  theme(legend.position = "none") 

```


```{r}
# running Shapiro-Wilk's test to test for normality 
shapiro.test(alaria_trial1_2_data$Settlement)
# not normal 

# log transforming the data 
transformed_trial_1 <- alaria_trial1_2_data %>%
  mutate(logSettlement = log(Settlement))

# testing for normality of transformed data
shapiro.test(transformed_trial_1$logSettlement)
# W = 0.98433, p-value = 0.1706
# normal
```

```{r}
# running a linear model on settlement and treatment with transformed data
alaria_trial1.mod <- lm(logSettlement ~ Treatment, data = transformed_trial_1)
summary(alaria_trial1.mod)
# sig difference
```


```{r}
# testing for variance - Bartlett test because of three treatments
bartlett.test(logSettlement ~ Treatment, data = transformed_trial_1)
# p-value = 0.1731 - equal variance
```


##### DIFFERENCE IN TANKS Trial 1

```{r}
# loading all data again in case I want to run this section alone
all_data <- read.csv("data/all_settlement_data.csv")

# filtering to only include Alaria
alaria_trial_all_data <- all_data %>%
  filter(Species == "Alaria", .preserve = FALSE)

# filtering to only include trial 1 data
alaria_trial1_2_data <- alaria_trial_all_data  %>%
  filter(Trial.Number == "1" | Trial.Number == "2", .preserve = FALSE)
```

```{r}
# loading colours for graph
my_cols4 = c("A" = "yellow3", "B" = "orange1", "C" = "blue", "D" = "purple")

# plotting differences in settlement per tank
ggplot(alaria_trial1_2_data, aes(x = Tanks, y = Settlement, fill = Tanks)) + 
  geom_point(aes(colour = Tanks), position = position_jitterdodge()) +
  geom_boxplot(alpha = 0.5) +
  scale_color_manual(values = my_cols4) +
  scale_fill_manual(values = my_cols4) + 
  theme_classic() +
  labs(x = "Tank", y = "Spore Settlement") +
  scale_x_discrete(labels = c("Tank A", "Tank B", "Tank C", "Tank D")) +
  scale_fill_discrete(name = "Treatments", labels = c("Treatment", "Treatment", 
                                                       "Control", "Control"))

```

### Comparing Control Tanks
```{r}
# filtering data to show settlement in control only
alaria_trial1_2_control_tanks <- alaria_trial1_2_data %>%
  filter(Treatment.Simp == "Control", .preserve = FALSE)
```

```{r}
# testing for normality
shapiro.test(alaria_trial1_2_control_tanks$Settlement)
# W = 0.90446, p-value = 0.002584
# not normal

# log transforming the data
transformed_trial1_2_control_tanks <- alaria_trial1_2_control_tanks %>%
  mutate(logSettlement = log(Settlement))

# testing for normality of transformed data
shapiro.test(transformed_trial1_2_control_tanks$logSettlement)
# W = 0.9758, p-value = 0.5372
# normal

```

```{r}
# running linear model on transformed data to test difference in settlement 
# between tanks in control
alaria_control1_2_tanks.mod <-  lm(logSettlement ~ Tanks, 
                                   data = transformed_trial1_2_control_tanks)
summary(alaria_control1_2_tanks.mod)
# Adjusted R-squared:  0.194 
# p-value: 0.002606
```

### Comparing Treatment Tanks
```{r}
# filtering data to only include sound treatment
alaria_trial1_2_treatment_tanks <- alaria_trial1_2_data %>%
  filter(Treatment.Simp == "Sound", .preserve = FALSE)
```

```{r}
# testing for normality
shapiro.test(alaria_trial1_2_treatment_tanks$Settlement)
# W = 0.93128, p-value = 0.0002825
# not normal

# log transforming the data
transformed_trial1_2_treatment_tanks <- alaria_trial1_2_treatment_tanks %>%
  mutate(logSettlement = log(Settlement))

# testing for normality of transformed data
shapiro.test(transformed_trial1_2_treatment_tanks$logSettlement)
# W = 0.98471, p-value = 0.4401
# normal
```

```{r}
# running a linear model - assuming normality - to test difference in means
alaria_treatment1_2_tanks.mod <- lm(logSettlement ~ Tanks, 
                                    data = transformed_trial1_2_treatment_tanks)
summary(alaria_treatment1_2_tanks.mod)
# Adjusted R-squared:  0.0487 
# p-value: 0.02599 
```




-----------------------------------------------------------------------------

### ALARIA SETTLEMENT TRIAL 2

```{r}
# loading all data again in case I want to run this section alone
all_data <- read.csv("data/all_settlement_data.csv")

# filtering to only include Alaria
alaria_trial_all_data <- all_data %>%
  filter(Species == "Alaria", .preserve = FALSE)

# filtering data to only include trial 3 and 4 (they have the same control)
alaria_trial3_4_data <- alaria_trial_all_data %>%
  filter(Trial == "3" | Trial == "4", .preserve = FALSE)

```

```{r}
# specifying what colours the treatments will be 
my_cols2 = c("Sound C" = "khaki2","Sound D" = "khaki1", "Control C-D" = "indianred3")

# loading graph of trial 3/4 
ggplot(alaria_trial3_4_data, aes(x = Treatment, 
                                 y = Settlement, fill = Treatment)) + 
  geom_point(aes(colour = Treatment), position = position_jitterdodge()) +
  geom_boxplot(alpha = 0.7) +
  scale_color_manual(values = my_cols2) +
  scale_fill_manual(values = my_cols2) + 
  theme_classic() +
  labs(x = "Trial 2", y = "Spore Settlement") +
  theme(axis.title = element_text(size = 10)) +
  scale_x_discrete(labels = c("Control", "20 kHz A", "20 kHz B")) +
  theme(legend.position = "none") 
  
```


```{r}
# testing for normality with a Shapiro-Wilk's test
shapiro.test(alaria_trial3_4_data$Settlement)
# not normal
```

```{r}
# data was not normal according to the shapiro wilks test (p = 0.001273), so 
# I'm log transforming the data to see if that fits a normal distribution
transformed_trial3_4_data <- alaria_trial3_4_data %>%
  mutate(logSettlement = log(Settlement))

# another Shapiro test shows that the transformed data fits the normal distribution
shapiro.test(transformed_trial3_4_data$logSettlement)
# W = 0.99172, p-value = 0.689
```

```{r}
# running a linear model using the log transformed data
alaria_trial2.mod <- lm(logSettlement ~ Treatment, data = transformed_trial3_4_data)
summary(alaria_trial2.mod)
```

                        
```{r}
# Running a two factor anova on transformed data - similar to the linear model
# why run this?
alaria_trial2.aov <- aov(logSettlement ~ Treatment, data = transformed_trial3_4_data)
summary(alaria_trial2.aov)
```


```{r}
# testing for variance - Bartlett test because of three treatments
bartlett.test(logSettlement ~ Treatment, data = transformed_trial3_4_data)
# p-value = 0.1049 - equal variance
```


##### DIFFERENCE IN TANKS Trial 2

```{r}
# loading all data again in case I want to run this section alone
all_data <- read.csv("data/all_settlement_data.csv")

# filtering to only include Alaria
alaria_trial_all_data <- all_data %>%
  filter(Species == "Alaria", .preserve = FALSE)

# filtering to only include trial 2 data
alaria_trial3_4_data <- alaria_trial_all_data  %>%
  filter(Trial.Number == "3" | Trial.Number == "4", .preserve = FALSE)
```

```{r}
# loading colours for graph
my_cols4 = c("A" = "yellow3", "B" = "orange1", "C" = "blue", "D" = "purple")

# plotting differences in settlement per tank
ggplot(alaria_trial3_4_data, aes(x = Tanks, y = Settlement, fill = Tanks)) + 
  geom_point(aes(colour = Tanks), position = position_jitterdodge()) +
  geom_boxplot(alpha = 0.5) +
  scale_color_manual(values = my_cols4) +
  scale_fill_manual(values = my_cols4) + 
  theme_classic() +
  labs(x = "Tank", y = "Spore Settlement") +
  scale_x_discrete(labels = c("Tank A", "Tank B", "Tank C", "Tank D")) +
  scale_fill_discrete(name = "Treatments", labels = c("Treatment", "Treatment", 
                                                       "Control", "Control"))

```

### Comparing Control Tanks
```{r}
# filtering data to show settlement in control only
alaria_trial3_4_control_tanks <- alaria_trial3_4_data %>%
  filter(Treatment.Simp == "Control", .preserve = FALSE)
```

```{r}
# testing for normality
shapiro.test(alaria_trial3_4_control_tanks$Settlement)
# W = 0.9665, p-value = 0.2507
# normal
```

```{r}
# running linear model on transformed data to test difference in settlement 
# between tanks in control
alaria_control3_4_tanks.mod <-  lm(Settlement ~ Tanks, 
                                   data = alaria_trial3_4_control_tanks)
summary(alaria_control3_4_tanks.mod)
# Adjusted R-squared:  -0.02458 
# p-value: 0.8989
```

### Comparing Treatment Tanks
```{r}
# filtering data to only include sound treatment
alaria_trial3_4_treatment_tanks <- alaria_trial3_4_data %>%
  filter(Treatment.Simp == "Sound", .preserve = FALSE)
```

```{r}
# testing for normality
shapiro.test(alaria_trial3_4_treatment_tanks$Settlement)
# W = 0.97483, p-value = 0.1201
```

```{r}
# running a linear model - assuming normality - to test difference in means
alaria_treatment3_4_tanks.mod <- lm(Settlement ~ Tanks, 
                                    data = alaria_trial3_4_treatment_tanks)
summary(alaria_treatment3_4_tanks.mod)
# Adjusted R-squared:  -0.003004 
# p-value: 0.3841
```



---------------------------------------------------------------------------

### COMBINED DATA 
```{r}
# loading all data again
all_data = read.csv("data/all_settlement_data.csv")

alaria_trial_all_data <- all_data %>%
  filter(Species == "Alaria", .preserve = FALSE)

```


```{r}
# testing for normality in all alaria settlement data
shapiro.test(alaria_trial_all_data$Settlement)
# W = 0.95681, p-value = 1.154e-06
# not normal

# distribution is not normal, so I'm log transforming the data
# to see if that normalized it. 
transformed_alaria_all_data <- alaria_trial_all_data %>%
  mutate(logSettlement = log(Settlement)) 
  
# Running another Shapiro-Wilk's test on transformed data
shapiro.test(transformed_alaria_all_data$logSettlement)
# W = 0.98838, p-value = 0.04697
# not normal

```

```{r}
# running a fitDist to see which distribution best fits data
fitDist(logSettlement, data = transformed_alaria_all_data, type = "realAll", try.gamlss = T) 
# Family:  c("WEI", "Weibull") 

# running a GAMLSS model
alaria_combined.mod <- gamlss(logSettlement ~ Treatment.Simp, data = transformed_alaria_all_data, family = "WEI")
summary(alaria_combined.mod)

```


```{r}
# filtering all data to only display settlement for sound treatment
alaria_only_sound <- alaria_trial_all_data %>%
  filter(Treatment == "Sound A" | Treatment == "Sound B" | Treatment == "Sound C"
         | Treatment == "Sound D", .preserve = FALSE)

# finding mean settlement for sound treatment
mean(alaria_only_sound$Settlement.Rate)
# 0.01336879

# filtering all data to only display settlement for control
alaria_only_control <- alaria_trial_all_data %>%
  filter(Treatment == "Control A-B" | Treatment == "Control C-D", 
         .preserve = FALSE)

# finding mean settlement for control
mean(alaria_only_control$Settlement.Rate)
# 0.01009165

```

```{r}
# testing for variance - Bartlett test because of three treatments
bartlett.test(logSettlement ~ Treatment, data = transformed_alaria_all_data)
# p = 0.02873
```


------------------------------------------------------------------------------

### ALL FOUR TRIALS IN ONE FIGURE

```{r}
# loading libraries necessary to make combined graph
library(patchwork)
library(ggplot2)

# specifying which colours I need for each treatment
my_cols1 = c("Sound A" = "khaki2", "Sound B" = "khaki1", 
             "Control A-B" = "indianred3")
my_cols2 = c("Sound C" = "khaki2","Sound D" = "khaki1", 
             "Control C-D" = "indianred3")
my_cols3 = c("Sound" = "khaki2", "Control" = "indianred3")

# loading all alaria data and filtering for each trial in case I want to run
# only this chunk of code
all_data = read.csv("data/all_settlement_data.csv")

## need to add another column to all data with just control vs settlment for 
# between species analysis because it is easier to then look at all controls
# instead of control A-B
alaria_trial_all_data <- all_data %>%
  filter(Species == "Alaria", .preserve = FALSE)

alaria_trial3_4_data <- alaria_trial_all_data %>%
  filter(Trial.Number == "3" | Trial.Number == "4", .preserve = FALSE)

alaria_trial1_2_data <- alaria_trial_all_data %>%
  filter(Trial.Number == "1" | Trial.Number == "2", .preserve = FALSE)

```

```{r}
# loading all graphs

# trial 1/2 graph
alaria_trial1_2_graph = ggplot(alaria_trial1_2_data, 
                             aes(x = Treatment, y = Settlement, fill = Treatment)) + 
  geom_point(aes(colour = Treatment), position = position_jitterdodge()) +
  geom_boxplot(alpha = 0.6) +
  scale_color_manual(values = my_cols1) +
  scale_fill_manual(values = my_cols1) + 
  theme_classic() +
  labs(x = "Treatment", y = "Spore Settlement") +
  theme(axis.title = element_text(size = 13)) +
  scale_x_discrete(labels = c("Control", "20 kHz A", "20 kHz B")) +
  theme(legend.position = "none") 

# trial 3/4 graph
alaria_trial3_4_graph = ggplot(alaria_trial3_4_data, 
                             aes(x = Treatment, y = Settlement, fill = Treatment)) + 
  geom_point(aes(colour = Treatment), position = position_jitterdodge()) +
  geom_boxplot(alpha = 0.6) +
  scale_color_manual(values = my_cols2) +
  scale_fill_manual(values = my_cols2) + 
  theme_classic() +
  labs(x = "Treatment", y = "Spore Settlement") +
  theme(axis.title = element_text(size = 13)) +
  scale_x_discrete(labels = c("Control", "20 kHz A", "20 kHz B")) +
  theme(legend.position = "none") 

# combined data graph
# using Treatment.simp because that is only labelled as control or sound, no 
# "Control C-D" or "Sound B"
combined_graph = ggplot(alaria_trial_all_data, aes(x = Treatment.Simp, y = Settlement, fill = Treatment.Simp)) + 
  geom_point(aes(colour = Treatment.Simp), position = position_jitterdodge()) +
  geom_boxplot(alpha = 0.6) +
  scale_color_manual(values = my_cols3) +
  scale_fill_manual(values = my_cols3) + 
  theme_classic() +
  labs(x = "Treatment", y = "Spore Settlement") +
  theme(axis.title = element_text(size = 13)) +
  scale_x_discrete(labels = c("Control", "20 kHz")) +
  theme(legend.position = "none")  
```

```{r}
# putting the two trials on the top and combined data on bottom in a combined 
# graph
spore_settlement_alaria = (alaria_trial1_2_graph | alaria_trial3_4_graph) / (combined_graph)
all_alaria_trial = spore_settlement_alaria+ plot_annotation(tag_levels = 'A')

ggsave(all_alaria_trial, filename = "alaria_combined_data.jpeg")

```



------------------------------------------------------------------------------

### GERMINATING Analysis


```{r}
# loading all germination data for alaria
alaria_germination_all <- read.csv("data/alaria_germination.csv")
```

```{r}
# loading colours for graph
my_cols4 = c("A Control" = "purple1", "A Treatment" = "purple2", 
             "B Control" = "lightgoldenrod1", "B Treatment" = "lightgoldenrod2")

# making title so species name is italicized
my_x_title_2 = expression(paste(italic("Alaria marginata"), " Treatments"))

# loading graph to show germination
alaria_germination = ggplot(alaria_germination_all, aes(x = Treatment, y = Ratio, fill = Treatment)) + 
  geom_point(aes(colour = Treatment), position = position_jitterdodge()) +
  geom_boxplot(alpha = 0.5) +
  scale_color_manual(values = my_cols4) +
  scale_fill_manual(values = my_cols4) + 
  theme_classic() +
  labs(x = my_x_title_2, y = "Proportion spores germinated") +
  theme(axis.title = element_text(size = 13)) +
  scale_x_discrete(labels = c("Control 1", "Treatment 1", 
                              "Control 2", "Treatment 2")) + 
  theme(legend.position = "None")

# saving grpah
ggsave(alaria_germination, filename = "alaria_germination.jpeg")

```


```{r}
# loading only trial 1 germination data
alaria_germination_trial_1 <- alaria_germination_all %>%
  filter(Treatment == "A Control" | Treatment == "A Treatment", .preserve = FALSE) 

# loading only trial 2 germination data
alaria_germination_trial_2 <- alaria_germination_all %>%
  filter(Treatment == "B Control" | Treatment == "B Treatment", .preserve = FALSE)
```


```{r}
# testing for normality in trial 1
shapiro.test(alaria_germination_trial_1$Ratio)
# W = 0.99187, p-value = 0.709 -> NORMAL

# testing for normality in trial 2
shapiro.test(alaria_germination_trial_2$Ratio)
# W = 0.99403, p-value = 0.896 -> NORMAL

```

```{r}
# running a linear model on trial 1 germination proportion - assuming normality
# numerical and categorical variable (ratio and treatment respectively)
alaria_germinating_trial1.mod <- lm(Ratio ~ Treatment, 
                      data = alaria_germination_trial_1)
summary(alaria_germinating_trial1.mod)
# Adjusted R-squared:  0.01117 
# F-statistic: 2.344 on 1 and 118 DF,  p-value: 0.1284
```

```{r}
# running a linear model on trial 2 germination proportion - assuming normality
alaria_germinating_trial2.mod <- lm(Ratio ~ Treatment, 
                      data = alaria_germination_trial_2)
summary(alaria_germinating_trial2.mod)
# Adjusted R-squared:  0.1071 
# F-statistic: 15.15 on 1 and 117 DF,  p-value: 0.0001658
```

```{r}
var.test(Ratio ~ Treatment, alaria_germination_trial_1, 
         alternative = "two.sided")
# p-value = 0.9122
         
var.test(Ratio ~ Treatment, alaria_germination_trial_2, 
         alternative = "two.sided")
# p-value = 0.8049
         
```




