---
title: "Graphs + Stats for DS experiment"
author: "Hannah Levit"
date: "15/11/2021"
output:
  pdf_document: default
  html_document: default
---

```{r}
library(ggplot2)
library(tidyverse)
library(DHARMa)
library(mgcv)
library(fitdistrplus)
library(goft)
# install.packages(gamlss)
library(gamlss)
library(patchwork)
library(MASS)
```

#### SETTLEMENT TRIAL 1

```{r}
# loading trial 1 data 
# note the treatment was done with a different batch of spores from the control 
# and thus the data is skewed and does not represent the effect of sound - not
# included in combined counts of data
# note data is a decimal instead of a count because i divided by concentration 
# due to different batches used
macro_trial1_data <- read.csv("data/macro_trial1_data.csv")
```

```{r}
# loading colours for the graph
my_cols1 = c("Control" = "seagreen", "Sound" = "orchid1")

# loading graph plotting settlement in sound treatment v control
# QUESTION should i plot logged data???
macro_trial_1 = ggplot(macro_trial1_data, aes(x = Treatment, y = Settlement, fill = Treatment)) + 
  geom_point(aes(colour = Treatment), position = position_jitterdodge()) +
  geom_boxplot(alpha = 0.7) +
  scale_color_manual(values = my_cols1) +
  scale_fill_manual(values = my_cols1) + 
  theme_classic() +
  labs(x = "Treatment", y = "Settlement / Concentration") +
  theme(axis.title = element_text(size = 13)) +
  scale_x_discrete(labels = c("Control", "20 kHz")) +
  theme(legend.position = "none") 

macro_trial_1

ggsave(macro_trial_1, filename = "macro_trial_1.jpeg")
```


### SETTLEMENT Analysis

```{r}
# using Shapiro-Wilks test to test for normality 
# if p < 0.05, data is not normal
shapiro.test(macro_trial1_data$Settlement)
# W = 0.79773, p-value = 4.103e-09
# not normal
```

```{r}
# log transforming the data to see if it better fits normal distribution - note
# the "M" refers to Macroystis data
transformed_trial_M1 <- macro_trial1_data %>%
  mutate(logSettlement = log(Settlement))

# testing for normality on transformed data
shapiro.test(transformed_trial_M1$logSettlement)
# W = 0.9547, p-value = 0.006468
# still not normal!
```


```{r}
# Using gamlss to find which distribution best fits data
fitDist(logSettlement, data = transformed_trial_M1, type = "realAll", try.gamlss = T) 
# Family:  c("SN2", "skew normal type 2") 

# visualizing the distribution
histDist(transformed_trial_M1$logSettlement, "SN2")
# HOW IS THIS RIGHT
```

```{r}
# running a gamlss data on non-normal data to test for significance
macro_trial1.mod <- gamlss(logSettlement ~ Treatment, data = transformed_trial_M1, family = "SN2")
summary(macro_trial1.mod)

```
              
```{r}
# Loading the library "car" in order to run Levene test
library(car)

# testing variance when we cannot assume normality - Levene's test
leveneTest(Settlement ~ Treatment, data = transformed_trial_M1)
# not equal variances

```


## COMPARING TANKS TRIAL 1
```{r}
# loading data for settlement in tanks 
# make a data set that includes tanks and use in all! consider time
macro_trial1_data <- read.csv("data/macro_trial1_data.csv")

```

```{r}
# loading colours for treatments and tanks
my_cols2 = c("A" = "seagreen", "B" = "springgreen3", "C" = "orchid1", "D" = "lightpink1")

# making title to italicize species name
my_x_title_2 = expression(paste(italic("Macrocystis pyrifera"), " Trial 1 - Tanks"))
# graphing the difference in settlement depending on tanks
# Treatment: tank A + B, Control: tank C + D
ggplot(macro_trial1_data, aes(x = Tank, y = Settlement, fill = Tank)) + 
  geom_point(aes(colour = Tank), position = position_jitterdodge()) +
  geom_boxplot(alpha = 0.7) +
  scale_color_manual(values = my_cols2) +
  scale_fill_manual(values = my_cols2) + 
  theme_classic() +
  labs(x = my_x_title_2, y = "Settlement / Concentration") +
  theme(axis.title = element_text(size = 13)) +
  scale_x_discrete(labels = c("Control A", "Control B", "Sound C", "Sound D")) +
  theme(legend.position = "none") 

```

```{r}
# filtering data so we are only looking at control tanks - to compare settlement 
# between tanks C and D
macro_control1_tanks <- transformed_trial_M1 %>%
  filter(Treatment == "Control", .preserve = FALSE)

```

```{r}
# testing for normality 
shapiro.test(macro_control1_tanks$Settlement)
# W = 0.8073, p-value = 9.653e-06
# not normal

# testing for normality on transformed data in only control 
shapiro.test(macro_control1_tanks$logSettlement)
# W = 0.9576, p-value = 0.1386
# normal distribution

# running a linear model to look for patterns and significance
macro_control1.mod <- lm(logSettlement ~ Tank, data = macro_control1_tanks)
summary(macro_control1.mod)
# no significant difference between tanks
```


```{r}
# filtering data so we are only looking at sound treatment  tanks - to c
# compare settlment between tanks A and B
macro_treatment1_tanks <- transformed_trial_M1 %>%
  filter(Treatment == "Sound", .preserve = FALSE)

# testing for normality 
shapiro.test(macro_treatment1_tanks$Settlement)
# W = 0.92681, p-value = 0.01269
# not normal

# testing for normality on transformed data in only control 
shapiro.test(macro_treatment1_tanks$logSettlement)
# W = 0.97476, p-value = 0.5021
# normal distribution
```

```{r}
# running a linear model to look for patterns and significance
macro_treatment1.mod <- lm(logSettlement ~ Tank, data = macro_treatment1_tanks)
summary(macro_treatment1.mod)
```


-------------------------------------------------------------------------------

### SPORE SETTLEMENT TRIAL 2

```{r}
# loading settlement data for trial 2
# first loading all data
all_data <- read.csv("data/all_settlement_data.csv")

# filtering to only include Macro
macro_trial_all_data <- all_data %>%
  filter(Species == "Macro", .preserve = FALSE)

# filtering to only include trial 2 data
# one treatment, one control
macro_trial2_data <- macro_trial_all_data %>%
  filter(Trial.Number == "2", .preserve = FALSE)
```

```{r}
# making colours for the boxplot
my_cols3 = c("Sound" = "orange2", "Control" = "blue3")

# graphing the trial 2 settlement data
ggplot(macro_trial2_data, aes(x = Treatment, y = Settlement, fill = Treatment)) + 
  geom_point(aes(colour = Treatment), position = position_jitterdodge()) +
  geom_boxplot(alpha = 0.5) +
  scale_color_manual(values = my_cols3) +
  scale_fill_manual(values = my_cols3) + 
  theme_classic() +
  labs(x = "Treatment", y = "Spore Settlement") +
  scale_x_discrete(labels = c("Control", "20 kHz")) +
  theme(legend.position = "none") 

```

### SETTLEMENT Analysis
```{r}
# testing for normality to determine which stat tests to use (ie parametric vs not)
shapiro.test(macro_trial2_data$Settlement)
# W = 0.96914, p-value = 0.05001
# normal distribution

transformed_trial_M2 <- macro_trial2_data %>%
  mutate(logSettlement = log(Settlement))

shapiro.test(transformed_trial_M2$logSettlement)
# W = 0.97423, p-value = 0.1057
# more normal
```


```{r}
# using a linear model to see patterns/differences between settlement (numerical)
# and treatment (categorical) 
macro_trial2.mod <- lm(Settlement ~ Treatment, data = macro_trial2_data)
summary(macro_trial2.mod)

# using a linear model to see patterns/differences between settlement (numerical)
# and treatment (categorical) of log transformed data
macro_trial2.mod <- lm(logSettlement ~ Treatment, data = transformed_trial_M2)
summary(macro_trial2.mod)
```


```{r}
# t test to find difference in means between Control group and Treatment group
# testing similarity of means assumes normality
t.test(Settlement ~ Treatment, data = macro_trial2_data, 
       alternative = "two.sided", var.equal = T, conf.level = 0.95)
# p-value = 0.3652

# runnning the same test on  transformed data
t.test(logSettlement ~ Treatment, data = transformed_trial_M2, 
       alternative = "two.sided", var.equal = T, conf.level = 0.95)
# p-value = 0.4269
```

  
```{r}
# F-test: testing for variance in data assuming normality
var.test(Settlement ~ Treatment, data = macro_trial2_data, 
         alternative = "two.sided")
# p-value = 0.3726

# testing for variance in log transformed data
var.test(logSettlement ~ Treatment, data = transformed_trial_M2, 
         alternative = "two.sided")
# p-value = 0.9032
```



##### DIFFERENCE IN TANKS Trial 2

```{r}
# loading trial 2 data again in case I want to run this section of code 
# independent of the rest of the markdown
all_data <- read.csv("data/all_settlement_data.csv")

# filtering to only include Macro
macro_trial_all_data <- all_data %>%
  filter(Species == "Macro", .preserve = FALSE)

# filtering to only include trial 3 data
# two rounds of treatment (Sound A, Sound B), one control
macro_trial2_data <- macro_trial_all_data %>%
  filter(Trial.Number == "2", .preserve = FALSE)
```

```{r}
# loading colours for graph
my_cols4 = c("A" = "yellow3", "B" = "orange1", "C" = "blue", "D" = "purple")

# plotting differences in settlement per tank
ggplot(macro_trial2_data, aes(x = Tanks, y = Settlement, fill = Tanks)) + 
  geom_point(aes(colour = Tanks), position = position_jitterdodge()) +
  geom_boxplot(alpha = 0.5) +
  scale_color_manual(values = my_cols4) +
  scale_fill_manual(values = my_cols4) + 
  theme_classic() +
  labs(x = "Tank", y = "Spore Settlement") +
  scale_x_discrete(labels = c("Tank A", "Tank B", "Tank B", "Tank C")) +
  scale_fill_discrete(name = "Treatments", labels = c("Treatment", "Treatment", 
                                                       "Control", "Control"))

```

### Comparing Control Tanks
```{r}
# filtering data to show settlement in control only
macro_control2_tanks <- macro_trial2_data %>%
  filter(Treatment == "Control", .preserve = FALSE)
```

```{r}
# testing for normality
shapiro.test(macro_control2_tanks$Settlement)
# W = 0.95593, p-value = 0.1214
# normal
```

```{r}
# running linear model to test difference in settlement between tanks in control
macro_control2_tanks.mod <-  lm(Settlement ~ Tanks, data = macro_control2_tanks)
summary(macro_control2_tanks.mod)
# Adjusted R-squared:  -0.0263 
# p-value: 0.9817
```

### Comparing Treatment Tanks
```{r}
# filtering data to only include sound treatment
macro_treatment2_tanks <- macro_trial2_data %>%
  filter(Treatment == "Sound", .preserve = FALSE)
```

```{r}
# testing for normality
shapiro.test(macro_treatment2_tanks$Settlement)
# W = 0.95812, p-value = 0.1444
# normal
```

```{r}
# running a linear model - assuming normality - to test difference in means
macro_treatment2_tanks.mod <- lm(Settlement ~ Tanks, data = macro_treatment2_tanks)
summary(macro_treatment2_tanks.mod)
# Adjusted R-squared:  -0.1552 
# p-value: 0.6546
```



-----------------------------------------------------------------------------  
  
### SPORE SETTLEMENT TRIAL 3

```{r}
# loading all data again in case I want to run this section alone
all_data <- read.csv("data/all_settlement_data.csv")

# filtering to only include Macro
macro_trial_all_data <- all_data %>%
  filter(Species == "Macro", .preserve = FALSE)

# filtering to only include trial 3 data
# two rounds of treatment (Sound A, Sound B), one control
macro_trial3_4_data <- macro_trial_all_data %>%
  filter(Trial.Number == "3" | Trial.Number == "4", .preserve = FALSE)

# loading colours for graph
my_cols5 = c("Sound A" = "orange2", "Sound B" = "orange1", "Control" = "blue3")

# plotting differences in settlement for treatment vs control in trial 3
ggplot(macro_trial3_4_data, aes(x = Treatment, y = Settlement, fill = Treatment)) + 
  geom_point(aes(colour = Treatment), position = position_jitterdodge()) +
  geom_boxplot(alpha = 0.5) +
  scale_color_manual(values = my_cols5) +
  scale_fill_manual(values = my_cols5) + 
  theme_classic() +
  labs(x = "Treatment", y = "Spore Settlement") +
  scale_x_discrete(labels = c("Control", "20 kHz (A)", "20 kHz (B)")) +
  theme(legend.position = "none") 
```


```{r}
# running a Shapiro-Wilk's test to test for normality
shapiro.test(macro_trial3_4_data$Settlement)
# W = 0.98765, p-value = 0.3554
# normal
```


```{r}
# running a linear model because we can assume normality
macro_trial2.mod <- lm(Settlement ~ Treatment, data = macro_trial3_4_data)
summary(macro_trial2.mod)
```

                        
```{r}
# can't run a t-test because there is more than 2 categorical variables 
# Running a multi-factor anova --> three treatments (Sound A, Sound B, Control)
macro_trial1.aov <- aov(Settlement ~ Treatment, data = macro_trial3_4_data)
summary(macro_trial1.aov)
```

```{r}
# Testing for variance between three variables using Bartlett's test
bartlett.test(Settlement ~ Treatment, data = macro_trial3_4_data)
```


##### DIFFERENCE IN TANKS Trial 3

```{r}
# loading all data again in case I want to run this section alone
all_data <- read.csv("data/all_settlement_data.csv")

# filtering to only include Macro
macro_trial_all_data <- all_data %>%
  filter(Species == "Macro", .preserve = FALSE)

# filtering to only include trial 3 data
macro_trial3_4_data <- macro_trial_all_data %>%
  filter(Trial.Number == "3" | Trial.Number == "4", .preserve = FALSE)
```

```{r}
# loading colours for graph
my_cols4 = c("A" = "yellow3", "B" = "orange1", "C" = "blue", "D" = "purple")

# plotting differences in settlement per tank
ggplot(macro_trial3_4_data, aes(x = Tanks, y = Settlement, fill = Tanks)) + 
  geom_point(aes(colour = Tanks), position = position_jitterdodge()) +
  geom_boxplot(alpha = 0.5) +
  scale_color_manual(values = my_cols4) +
  scale_fill_manual(values = my_cols4) + 
  theme_classic() +
  labs(x = "Tank", y = "Spore Settlement") +
  scale_x_discrete(labels = c("Tank A", "Tank B", "Tank C", "Tank D")) +
  scale_fill_discrete(name = "Treatments", labels = c("Treatment", "Treatment", 
                                                       "Control", "Control"))

```

### Comparing Control Tanks
```{r}
# filtering data to show settlement in control only
macro_control3_4_tanks <- macro_trial3_4_data %>%
  filter(Treatment.Simp == "Control", .preserve = FALSE)
```

```{r}
# testing for normality
shapiro.test(macro_control3_4_tanks$Settlement)
# W = 0.96328, p-value = 0.2165
# normal
```

```{r}
# running linear model to test difference in settlement between tanks in control
macro_control3_4_tanks.mod <-  lm(Settlement ~ Tanks, data = macro_control3_4_tanks)
summary(macro_control3_4_tanks.mod)
# Adjusted R-squared:  0.2314 
# p-value: 0.0009885
```

### Comparing Treatment Tanks
```{r}
# filtering data to only include sound treatment
macro_treatment3_4_tanks <- macro_trial3_4_data %>%
  filter(Treatment.Simp == "Sound", .preserve = FALSE)
```

```{r}
# testing for normality
shapiro.test(macro_treatment3_4_tanks$Settlement)
# W = 0.96987, p-value = 0.05836
# normal
```

```{r}
# running a linear model - assuming normality - to test difference in means
macro_treatment3_4_tanks.mod <- lm(Settlement ~ Tanks, data = macro_treatment3_4_tanks)
summary(macro_treatment3_4_tanks.mod)
# Adjusted R-squared:  0.0714 
# p-value: 0.009892
```



-------------------------------------------------------------------------------

####COMBINED TRIALS - no batch effect trialS

```{r}
# loading data of all trials combined (subtract trial 1)
all_data <- read.csv("data/all_settlement_data.csv")

# filtering to only include Macro
macro_trial_all_data <- all_data %>%
  filter(Species == "Macro", .preserve = FALSE)

```

```{r}
# loading colours for the following graph
my_cols1 = c("Sound" = "orchid1", "Control" = "seagreen")

# plotting graph of all viable data from the macrocystis trials combined data
# - without trial 1
ggplot(macro_trial_all_data, aes(x = Treatment, y = Settlement, fill = Treatment)) + 
  geom_point(aes(colour = Treatment), position = position_jitterdodge()) +
  geom_boxplot(alpha = 0.6) +
  scale_color_manual(values = my_cols1) +
  scale_fill_manual(values = my_cols1) + 
  theme_classic() +
  labs(x = "Treatment", y = "Settlement") +
  scale_x_discrete(labels = c("Control", "20 kHz")) +
  theme(legend.position = "none") 

```

## Analysis
```{r}
# testing if the data fits a normal distribution
shapiro.test(macro_trial_all_data$Settlement)
# W = 0.94299, p-value = 4.459e-07
# Not a normal distribution!
```


```{r}
# log transforming the data to see if it now fits a normal distribution
transformed_all_data <- macro_trial_all_data %>%
  mutate(logSettlement = log(Settlement))

shapiro.test(transformed_all_data$logSettlement)
# W = 0.96, p-value = 2.075e-05
# still not normal, further modeling necessary!!!! 
```


```{r}
# Using gamlss to find which distribution best models my data
fitDist(Settlement, data = macro_trial_all_data, type = "realAll", try.gamlss = T) 
# ("SEP2", "Skew Exponential Power type 2") 
# Fitting method: "nlminb" 

histDist(macro_trial_all_data$Settlement, "SEP2")

```


```{r}
# running a gamlss model for the combined data and summarizing the results
macro_combined.mod <- gamlss(Settlement ~ Treatment.Simp, data = macro_trial_all_data, family = "SEP2")
summary(macro_combined.mod)
# p = 0.00554
```

```{r}
# loading car library in order to run Leven test on the non-normal distribution
library(car)

# testing variance when we cannot assume normality 
leveneTest(Settlement ~ Treatment, data = macro_trial_all_data)
# p = 1.007e-07 - unequal variance
```

```{r}
# filtering all data to only display settlement for sound treatment

macro_only_sound <- macro_trial_all_data %>%
  filter(Treatment.Simp == "Sound", .preserve = FALSE)

# finding mean settlement for sound treatment
mean(macro_only_sound$Settlement)
# 93.28571

# filtering all data to only display settlement for control
macro_only_control <- macro_trial_all_data %>%
  filter(Treatment.Simp == "Control", .preserve = FALSE)

# finding mean settlement for control
mean(macro_only_control$Settlement)
# 54.775

```


------------------------------------------------------------------------------

### ALL LEGIT TRIALS IN ONE FIGURE

```{r, echo = FALSE, message = FALSE, warning = FALSE}
# loadgin libraries needed for making combined graph
library(patchwork)
library(ggplot2)
require(gridExtra)

# loading all data again in case I want to run this section alone
all_data <- read.csv("data/all_settlement_data.csv")

# filtering to only include Macro
macro_trial_all_data <- all_data %>%
  filter(Species == "Macro", .preserve = FALSE)

# loading settlement data for trial 2
macro_trial2_data <- macro_trial_all_data %>%
  filter(Trial.Number == "2", .preserve = FALSE)

# loading settlement data for trial 3
macro_trial3_4_data <- macro_trial_all_data %>%
  filter(Trial.Number == "3" | Trial.Number == "4", .preserve = FALSE)

```

```{r}
# all colours used in the graphs
my_cols6 = c("Sound" = "orange2", "Control" = "blue3", "Control " = "blue3",
             "Sound A" = "orange2", "Sound B" = "orange2")

# graph for trial 2 data
macro_trial2_graph = ggplot(macro_trial2_data, aes(x = Treatment, y = Settlement, fill = Treatment)) + 
  geom_point(aes(colour = Treatment), position = position_jitterdodge()) +
  geom_boxplot(alpha = 0.5) +
  scale_color_manual(values = my_cols6) +
  scale_fill_manual(values = my_cols6) + 
  theme_classic() +
  labs(x = "Treatment", y = "Spore Settlement") +
  scale_x_discrete(labels = c("Control", "20 kHz")) +
  theme(legend.position = "none") 

# graph for trial 3 and 4 data (two treatments, one control)
macro_trial3_4_graph = ggplot(macro_trial3_4_data, aes(x = Treatment, y = Settlement, fill = Treatment)) + 
  geom_point(aes(colour = Treatment), position = position_jitterdodge()) +
  geom_boxplot(alpha = 0.5) +
  scale_color_manual(values = my_cols6) +
  scale_fill_manual(values = my_cols6) + 
  theme_classic() +
  labs(x = "Treatment", y = "Spore Settlement") +
  scale_x_discrete(labels = c("Control", "20 kHz (A)", "20 kHz (B)")) +
  theme(legend.position = "none") 

# graph for combined Macro data 
combined_graph = ggplot(macro_trial_all_data, aes(x = Treatment.Simp, y = Settlement, fill = Treatment.Simp)) + 
  geom_point(aes(colour = Treatment.Simp), position = position_jitterdodge()) +
  geom_boxplot(alpha = 0.7) +
  scale_color_manual(values = my_cols6) +
  scale_fill_manual(values = my_cols6) + 
  theme_classic() +
  labs(x = "Treatment", y = "Spore Settlement") +
  theme(axis.title = element_text(size = 13)) +
  scale_x_discrete(labels = c("Control", "20 kHz")) +
  theme(legend.position = "none") 
# describe in figure caption

```

```{r}
# loading patchwork library
library(patchwork)
#combining all graphs so trial 2 and 3/4 are on the tob and the combined graph 
# is larger and on the bottom
spore_settlement_macro = (macro_trial2_graph | macro_trial3_4_graph) / (combined_graph)
combined_graph = spore_settlement_macro+ plot_annotation(tag_levels = 'A')

combined_graph
ggsave(combined_graph, file = "macro_combined_data.jpeg")

```


-----------------------------------------------------------------------------

### GERMINATION ANALYSIS

```{r}
# loading germination data
macro_germination_all <- read.csv("data/macro_germination.csv")

```

```{r}
library(ggplot2)
# specifying all colours necessary for graph
my_cols7 = c("A Control" = "red1", "A Treatment" = "red2", 
             "B Control" = "pink1", "B Treatment" = "pink2",
             "C Control" = "blue1", "C Treatment" = "blue2")

# Making x axis title - making species name in italics
my_x_title = expression(paste(italic("Macrocystis pyrifera"), " Treatments"))

# loading graph for germination data
macro_germination = ggplot(macro_germination_all, aes(x = Treatment, y = Ratio, fill = Treatment)) + 
  geom_point(aes(colour = Treatment), position = position_jitterdodge()) +
  geom_boxplot(alpha = 0.5) +
  scale_color_manual(values = my_cols7) +
  scale_fill_manual(values = my_cols7) + 
  theme_classic() +
  labs(x = my_x_title, y = "Proportion spores germinated") +
  theme(axis.title = element_text(size = 13)) +
  scale_x_discrete(labels = c("Control 1", "Treatment 1", "Control 2",
                              "Treatment 2", "Control 3", "Treatment 3")) +
  theme(legend.position = "none")

ggsave(macro_germination, filename = "macro_germination.jpeg")

# display time in legend
```


### GERMINATING Analysis

```{r}
# loading germination data
macro_germination_all <- read.csv("data/macro_germination.csv")

# filtering data so it is only germination data from treatment 1
macro_germination_trial_1 <- macro_germination_all %>%
  filter(Treatment == "A Control" | Treatment == "A Treatment", .preserve = FALSE) 

# filtering data so it is only germination data from treatment 2
macro_germination_trial_2 <- macro_germination_all %>%
  filter(Treatment == "B Control" | Treatment == "B Treatment", .preserve = FALSE)

# filtering data so it is only germination data from treatment 3/4
macro_germination_trial_3 <- macro_germination_all %>%
  filter(Treatment == "C Control" | Treatment == "C Treatment", .preserve = FALSE)
```


```{r}
# testing for normality in trial 1
shapiro.test(macro_germination_trial_1$Ratio)
# W = 0.97902, p-value = 0.226 -> NORMAL

# testing for normality in trial 2
shapiro.test(macro_germination_trial_2$Ratio)
# W = 0.99224, p-value = 0.9163 -> NORMAL

# testing for normality in trial 3
shapiro.test(macro_germination_trial_3$Ratio)
# W = 0.96522, p-value = 0.003578 -> NOT NORMAL
```



```{r}
# running a linear model on trial 1 germination proportion - assuming normality
# numerical and categorical variable (ratio and treatment respectively)
macro_germinating_trial1.mod <- lm(Ratio ~ Treatment, 
                      data = macro_germination_trial_1)
summary(macro_germinating_trial1.mod)
# Adjusted R-squared:  0.0007447 
# p-value: 0.3071


# running a linear model on trial 2 germination proportion - assuming normality
macro_germinating_trial2.mod <- lm(Ratio ~ Treatment, 
                      data = macro_germination_trial_2)
summary(macro_germinating_trial2.mod)
# Adjusted R-squared:  0.01793 
# p-value: 0.1221
```

```{r}
# log transforming data to test for normality
transformed_macro_germ_3 <- macro_germination_trial_3 %>%
  filter(Ratio > 0) %>%
  mutate(logRatio = log(Ratio))
  

# testing for normality of transformed data
shapiro.test(transformed_macro_germ_3$logRatio)
# normal
```


```{r}
# running a linear model on trial 3 log germination proportion - assuming normality
macro_germinating_trial3.mod <- lm(logRatio ~ Treatment, 
                      data = transformed_macro_germ_3)
summary(macro_germinating_trial3.mod)
# Adjusted R-squared:  0.01793 
# p-value: 0.1221

```



```{r}
# running a variance test for trial 1
var.test(Ratio ~ Treatment, macro_germination_trial_1, 
         alternative = "two.sided")

# running a variance test for trial 2     
var.test(Ratio ~ Treatment, macro_germination_trial_2, 
         alternative = "two.sided")
         
# running a variance test for trial 3/4
var.test(logRatio ~ Treatment, transformed_macro_germ_3, 
         alternative = "two.sided") 

```


  
  
