---
title: "Species Comparison"
author: "Hannah Levit"
date: "14/12/2021"
output: html_document
---
### Loading Libraries 
```{r}
library(ggplot2)
library(tidyverse)
library(DHARMa)
library(mgcv)
library(fitdistrplus)
library(goft)
library(gamlss)
library(patchwork)
library(MASS)
# do i need all of these?
```

###SPECIES COMPARISON

```{r}
# loading all data from both Alaria marginata and Macrocystis pyrifera
all_data = read.csv("data/all_settlement_data.csv")

# going into data and finding the 9 label names in the column Label so 
# it is easier to assign a colour to each treatment
library(tidyverse)
library(dplyr)
testerlabels <- all_data %>%
  dplyr::select(Label) %>%
  distinct

testerlabels

# Labels look like: M_A_Control - which refers to Macro control 1(which is 
# actually trial 2 due to method change)
# A_A_Control refers to control for sound trial 1-2 and A_B_Control refers to 
# control for sound trial 3-4 
my_cols_all = c("M_A_Control" = "orchid1", 
             "M_B_Control"	= "palegreen2",
             "M_A_Sound"	= "orchid1", 
             "M_B_Sound"	= "palegreen2",	
             "M_C_Sound"	= "palegreen2",	
             "A_A_Control"	= "steelblue1", 
             "A_B_Control"	= "sienna1", 	
             "A_A_Sound"	= "steelblue1", 	
             "A_B_Sound" = "sienna1")	

# loading graph of all data - both species 
# need to go back and represent in opposite order on y axis
  ggplot(all_data, aes(y = Label, x = Settlement.Rate, fill = Label)) + 
  geom_point(aes(colour = Label), position = position_jitterdodge()) +
  geom_boxplot(alpha = 0.7) +
  scale_color_manual(values = my_cols_all) +
  scale_fill_manual(values = my_cols_all) + 
  theme_classic() +
  labs(y = "Treatment", x = "Settlement") +
  theme(axis.title = element_text(size = 10)) +
  scale_y_discrete(labels = c("Alaria Control A", " Alaria Sound A", 
                              "Alaria Control B", "Alaria Sound B",
                              "Macro Control A", "Macro Sound A",
                              "Macro Control B", "Macro Sound B.1", 
                              "Macro Sound B.2")) +
  theme(legend.position = "none")
```

```{r}
# loading data again to make a second type of graph - figure out which one best
# represents the model while comparing species!!
all_data = read.csv("data/all_settlement_data.csv")

# making all box titles - need to italicize species names
x_title_control_alaria = expression(paste(italic("A.marginata"), " Control"))
x_title_sound_alaria = expression(paste(italic("A.marginata"), " 20 kHz"))
x_title_control_macro = expression(paste(italic("M.pyrifera"), " Control"))
x_title_sound_macro = expression(paste(italic("M.pyrifera"), " 20 kHz"))

# assigning colours
my_cols_label.B = c("M_Control" = "steelblue3", 
             "M_Sound"	= "steelblue2",
             "A_Sound"	= "coral", 
             "A_Control"	= "coral1")

# loading the graph comparing species and all settlement
species_comparison = ggplot(all_data, aes(x = Label.B, y = Settlement, 
                                          fill = Label.B)) + 
  geom_point(aes(colour = Label.B), position = position_jitterdodge()) +
  geom_boxplot(alpha = 0.7) +
  scale_color_manual(values = my_cols_label.B) +
  scale_fill_manual(values = my_cols_label.B) + 
  theme_classic() +
  labs(x = "Treatment and Species", y = "Settlement") +
  theme(axis.title = element_text(size = 10)) +
  scale_x_discrete(labels = c(x_title_control_alaria , x_title_sound_alaria,
                              x_title_control_macro, x_title_sound_macro)) +
  theme(legend.position = "none")

species_comparison

ggsave(species_comparison, file ="species_comparison_graph.jpeg")

# I Like how this one presents the data!!
```


```{r}
# loading data for all measurements 
all_data = read.csv("data/all_settlement_data.csv")

# making titles in which species names are italicized 
my_x_title_alaria = expression(paste(italic("Alaria marginata")))
my_x_title_macro = expression(paste(italic("Macrocystis pyrifera")))

# loading the graph comparing species and all settlement
comparing_all_settlement = ggplot(all_data, aes(x = Species, y = Settlement.Rate, fill = Species)) + 
  geom_point(aes(colour = Species), position = position_jitterdodge()) +
  geom_boxplot(alpha = 0.7) +
  theme_classic() +
  labs(x = "Species", y = "Total Settlement") +
  theme(axis.title = element_text(size = 10)) +
  scale_x_discrete(labels = c(my_x_title_alaria, my_x_title_macro)) +
  theme(legend.position = "none")

comparing_all_settlement

ggsave(comparing_all_settlement, file = "species_comparison_all_settlement.jpeg")
```

```{r}
# Checking for significant difference between treatments for each species 
# ie the sound treatment settlement in Macro vs Alaria, and the same for controls

# Treatment
only_sound_both_species <- all_data %>%
  filter(Treatment.Simp == "Sound", .preserve = FALSE) %>%
  subset(select = c(Settlement.Rate, Species))

# Control
only_control_both_species <- all_data %>%
  filter(Treatment.Simp == "Control", .preserve = FALSE) %>%
  subset(select = c(Settlement.Rate, Species))
```

```{r}
# testing for normality of species to species comparison of the effect of the treatment
shapiro.test(only_sound_both_species$Settlement.Rate)
# W = 0.7939, p-value < 2.2e-16
# not normal

# log transforming the data to see if it normalizes it 
transformed_only_sound <- only_sound_both_species %>%
  mutate(logSettlementRate = log(Settlement.Rate))

# testing for normality of transformed data
shapiro.test(transformed_only_sound$logSettlementRate)
# W = 0.90929, p-value = 5.788e-12
# still not normal
```

```{r}
ggplot(only_sound_both_species, aes(x = Species, y = Settlement.Rate, fill = Species)) + 
  geom_point(aes(colour = Species), position = position_jitterdodge()) +
  geom_boxplot(alpha = 0.7) +
  theme_classic() +
  labs(x = "Species - sound treatments", y = "Total Settlement") +
  theme(axis.title = element_text(size = 10)) +
  scale_x_discrete(labels = c(my_x_title_alaria, my_x_title_macro)) +
  theme(legend.position = "none")

# trying to fit the un-transformed data to a distribution
fitDist(Settlement.Rate, data = only_sound_both_species, type = "realAll", try.gamlss = T) 
# Family:  c("PE2", "Power Exponential type 2") 
# Fitting method: "nlminb" 

# visualizing the distribution in a histogram
histDist(only_sound_both_species$Settlement.Rate, "PE2")

# running a gamlss model on data - can't assume normality
only_sound_both_species.mod <- gamlss(Settlement.Rate ~ Species, 
                      data = only_sound_both_species, family = "PE2")
summary(only_sound_both_species.mod)
# p = <2e-16
```


```{r}
# testing for normality in only controls of both species
shapiro.test(only_control_both_species$Settlement.Rate)
# W = 0.85734, p-value = 2.974e-11
# not normal

# log transforming the data to see if it normalizes it 
transformed_only_control <- only_control_both_species %>%
  mutate(logSettlementRate = log(Settlement.Rate))

# testing for normality of transformed data
shapiro.test(transformed_only_control$logSettlementRate)
# W = 0.94341, p-value = 4.49e-06
# not normal
```

```{r}
ggplot(only_control_both_species, aes(x = Species, y = Settlement.Rate, fill = Species)) + 
  geom_point(aes(colour = Species), position = position_jitterdodge()) +
  geom_boxplot(alpha = 0.7) +
  theme_classic() +
  labs(x = "Species - control", y = "Settlement Rate") +
  theme(axis.title = element_text(size = 10)) +
  scale_x_discrete(labels = c(my_x_title_alaria, my_x_title_macro)) +
  theme(legend.position = "none")

# trying to fit the un-transformed data to a distribution
fitDist(Settlement.Rate, data = only_control_both_species, type = "realAll", try.gamlss = T) 
# c("SHASH", "Sinh-Arcsinh") 
# Fitting method: "nlminb"

# visualizing the distribution in a histogram
histDist(only_control_both_species$Settlement.Rate, "SHASH")

# running a gamlss model on data - can't assume normality
only_control_both_species.mod <- gamlss(Settlement.Rate ~ Species, 
                      data = only_control_both_species, family = "PE2")
summary(only_control_both_species.mod)
# p = <2e-16
```


